!!ARBvp1.0
ATTRIB  iPos         = vertex.position;
ATTRIB  iColour      = vertex.color;
ATTRIB  iTexCoord    = vertex.texcoord[0];
OUTPUT  oPos         = result.position;
OUTPUT  oColour      = result.color;
OUTPUT  oTexCoord0   = result.texcoord[0];
OUTPUT  oTexCoord1   = result.texcoord[1];
OUTPUT  oFogCoord    = result.fogcoord;
PARAM   fogParams    = program.local[0];
PARAM   waterPlane   = program.local[1];
PARAM   pMatrix[4]   = { state.matrix.projection };
PARAM   mvMatrix[4]  = { state.matrix.modelview };
PARAM   texMatrix[4] = { state.matrix.texture[0] };
TEMP    viewPos, fogFactor, depth;
DP4   viewPos.x, mvMatrix[0], iPos;
DP4   viewPos.y, mvMatrix[1], iPos;
DP4   viewPos.z, mvMatrix[2], iPos;
DP4   viewPos.w, mvMatrix[3], iPos;
SUB   fogFactor.x, viewPos.z, fogParams.x;
MUL   fogFactor.x, fogFactor.x, 0.001953125;
DP4   depth, waterPlane, viewPos;
MAD   fogFactor.y, -depth, fogParams.z, fogParams.w;
SUB   fogFactor.z, viewPos.z, fogParams.y;
MUL   fogFactor.z, fogFactor.z, 0.00390625;
MIN   fogFactor, fogFactor, 1;
MAX   fogFactor, fogFactor, 0;
MUL   fogFactor.z, fogFactor.z, -depth;
MAD   viewPos.xyz, waterPlane.xyzw, fogFactor.zzzz, viewPos.xyzw;
MAX   oTexCoord1.xyz, fogFactor.xxxx, fogFactor.yyyy;
MOV   oTexCoord1.w, 1;
MOV   oColour, iColour;
DP4   oPos.x, pMatrix[0], viewPos;
DP4   oPos.y, pMatrix[1], viewPos;
DP4   oPos.z, pMatrix[2], viewPos;
DP4   oPos.w, pMatrix[3], viewPos;
MOV   oFogCoord.x, viewPos.z;
DP4   oTexCoord0.x, texMatrix[0], iTexCoord;
DP4   oTexCoord0.y, texMatrix[1], iTexCoord;
DP4   oTexCoord0.z, texMatrix[2], iTexCoord;
MOV   oTexCoord0.w, 1;
END