!!ARBvp1.0
ATTRIB  iPos         = vertex.position;
ATTRIB  iNormal      = vertex.normal;
ATTRIB  iColour      = vertex.color;
ATTRIB  iTexCoord    = vertex.texcoord[0];
OUTPUT  oPos         = result.position;
OUTPUT  oColour      = result.color;
OUTPUT  oTexCoord0   = result.texcoord[0];
OUTPUT  oTexCoord1   = result.texcoord[1];
OUTPUT  oFogCoord    = result.fogcoord;
PARAM   fogParams    = program.local[0];
PARAM   waterPlane   = program.local[1];
PARAM   tMatrix[4]   = { state.matrix.texture[0] };
PARAM   pMatrix[4]   = { state.matrix.projection };
PARAM   mvMatrix[4]  = { state.matrix.modelview };
TEMP    viewPos, viewNormal, fogFactor, colour, ndotl;
DP4   viewPos.x, mvMatrix[0], iPos;
DP4   viewPos.y, mvMatrix[1], iPos;
DP4   viewPos.z, mvMatrix[2], iPos;
DP4   viewPos.w, mvMatrix[3], iPos;
SUB   fogFactor.x, viewPos.z, fogParams.x;
MUL   fogFactor.x, fogFactor.x, 0.001953125;
MAD   fogFactor.y, iTexCoord.z, fogParams.z, fogParams.w;
SUB   fogFactor.z, viewPos.z, fogParams.y;
MUL   fogFactor.z, fogFactor.z, 0.00390625;
MUL   fogFactor.x, fogFactor.x, fogFactor.y;
MIN   fogFactor, fogFactor, 1;
MAX   fogFactor, fogFactor, 0;
MUL   fogFactor.z, fogFactor.z, iTexCoord.z;
MAD   viewPos.xyz, waterPlane.xyzw, fogFactor.zzzz, viewPos.xyzw;
MAX   oTexCoord1.xyz, fogFactor.xxxx, fogFactor.yyyy;
MOV   oTexCoord1.w, 1;
DP3   viewNormal.x, mvMatrix[0], iNormal;
DP3   viewNormal.y, mvMatrix[1], iNormal;
DP3   viewNormal.z, mvMatrix[2], iNormal;
DP3   ndotl.x, viewNormal, state.light[0].position;
DP3   ndotl.y, viewNormal, state.light[1].position;
MAX   ndotl, ndotl, 0;
MOV   colour, state.lightmodel.ambient;
MAD   colour, state.light[0].diffuse, ndotl.xxxx, colour;
MAD   colour, state.light[1].diffuse, ndotl.yyyy, colour;
MUL   oColour, iColour, colour;
DP4   oPos.x, pMatrix[0], viewPos;
DP4   oPos.y, pMatrix[1], viewPos;
DP4   oPos.z, pMatrix[2], viewPos;
DP4   oPos.w, pMatrix[3], viewPos;
MOV   oFogCoord.x, viewPos.z;
DP3   oTexCoord0.x, tMatrix[0], iTexCoord;
DP3   oTexCoord0.y, tMatrix[1], iTexCoord;
MOV   oTexCoord0.zw, iTexCoord;
END